spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/interviewdb
    username: interview
    password: interview

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
